runtime: nodejs20
env: standard
service: agilegpsbackend
entrypoint: npm start

instance_class: F4_1G    # Switch to F1 to reduce cost if your app can handle it

env_variables:
  NODE_ENV: 'production'
  GCS_BUCKET_NAME: "listalotimages"

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.8
  min_instances: 0         # Scale down to zero for cost savings
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

network:
  session_affinity: false
  instance_tag: backend-instance